HxLabsMVCApplication/HxLabsMVCApplication/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using HxLabsMVCApplication.Models;
using Data;
using Services;
using System.Data;

namespace HxLabsMVCApplication.Controllers
{
    public class GenresController : Controller
    {
        private readonly GenresService genres = new GenresService();

        /*GET*/
        public ActionResult Index()
        {
            var model = new GenreIndexModel();
            model.Genres = genres.GetAll();
            return View(model);
        }

        ///*OBTENER LISTA DE GENEROS FILTRADA*/
        //public ActionResult Index()
        //{
        //    var model = new GenreIndexModel();
        //    model.Genres = genres.Select();
        //    return View(model);
        //}

        /*CREAR*/
        public ActionResult Create()
        {
            return View("Create", new GenreCreateModel() { ViewAction = ViewAction.Create, Genre = new Genre() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                genres.Create(genre);
                TempData["successmessage"] = "Se ha agregado exitosamente el genero: " + genre.Name;
                return RedirectToAction("Index");
            }
            else
                return View("Create", new GenreCreateModel() { ViewAction = ViewAction.Create, Genre = genre });
        }

        /*EDITAR*/
        public ActionResult Edit(Guid id)
        {
            Genre genre = genres.Get(id);
            return View("Create", new GenreCreateModel() { ViewAction = ViewAction.Edit, Genre = genre });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Genre genre)
        {
            if (this.ModelState.IsValid)
            {
                var g = genres.Update(genre, genre.Id);
                TempData["successmessage"] = "Se ha actualizado exitosamente el genero: " + g.Name;
                return RedirectToAction("Index");
            }
            else
                return View("Create", new GenreCreateModel() { ViewAction = ViewAction.Edit, Genre = genre });
        }


        /*ELIMINAR*/
        public ActionResult Delete(Guid id, bool? saveChangesError = false)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "ERROR al eliminar el género";
            }

            Genre genre = genres.Get(id);
            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id)
        {
            try
            {
                Genre genreToDelete = genres.Get(id);
                genres.Delete(genreToDelete);
                TempData["successmessage"] = "Se ha eliminado exitosamente la pelicula: " + genreToDelete.Name;
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }
    }
}

HxLabsMVCApplication/HxLabsMVCApplication/Controllers/MoviesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using HxLabsMVCApplication.Models;
using Entities;
using System.Data;
using Data;
using Services;
using System.Collections.Generic;


namespace HxLabsMVCApplication.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MoviesService movies = new MoviesService();
        private readonly GenresService genres = new GenresService();

        /*OBTENER TODAS LAS PELÍCULAS ORDENADAS*/
        public ActionResult Index(string SearchString = "")
        {
            var model = new MovieIndexModel();
            if (SearchString == string.Empty)
            {
                model.Movies = movies.GetAll();
            }
            else
            {
                model.Movies = movies.GetAll().Where(m => m.Name.Contains(SearchString));
            }
            

            return View(model);
        }

       

        /*CREAR*/
        public ActionResult Create()
        {
            return View("Create", new MovieCreateModel() { ViewAction = ViewAction.Create, Movie = new Movie(), Genres = genres.GetAll() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Movie movie, ICollection<Guid> selectedGenres)
        {
            if (ModelState.IsValid)
            {
                if (selectedGenres != null)
                {
                    foreach (var selectedGenreId in selectedGenres)
                    {
                        Genre genre = genres.Get(selectedGenreId);

                        if (genre != null)
                            movie.Genres.Add(genre);
                    }
                }

                movies.Create(movie);
                TempData["successmessage"] = "Se ha agregado exitosamente la pelicula: " + movie.Name;
                return RedirectToAction("Index");
            }
            else
                return View("Create", new MovieCreateModel() { ViewAction = ViewAction.Create, Movie = movie, Genres = genres.GetAll() });
        }


        /*EDITAR*/
        public ActionResult Edit(Guid id)
        {
            Movie movie = movies.Get(id);
            return View("Create", new MovieCreateModel() { ViewAction = ViewAction.Edit, Movie = movie, Genres = movie.Genres });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie movie)
        {
            if (this.ModelState.IsValid)
            {
                var m = movies.Update(movie, movie.Id);
                TempData["successmessage"] = "Se ha actualizado exitosamente la pelicula: " + m.Name;
                return RedirectToAction("Index");                            
            }
            else
                return View("Create", new MovieCreateModel() { ViewAction = ViewAction.Edit, Movie = movie });
        }


        /*ELIMINAR*/
        public ActionResult Delete(Guid id, bool? saveChangesError = false)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "ERROR al eliminar la película";
            }

            Movie movie = movies.Get(id);
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id)
        {
            try
            {
                Movie movieToDelete = movies.Get(id);
                movies.Delete(movieToDelete);
                TempData["successmessage"] = "Se ha eliminado exitosamente la pelicula: " + movieToDelete.Name;
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }
    }
}

HxLabsMVCApplication/HxLabsMVCApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/bootstrap/bootstrap")
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
</head>

<body>
    <div id="wrap">
        <div class="container">
            <div class="navbar navbar-default" style="margin-top: 20px;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                        <img style="height: 18px; margin-top: -5px;" src="@Url.Content("~/Content/images/hexactalogo2.png")" alt="Hexacta" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @{var controller = ViewContext.RouteData.Values["controller"].ToString().ToLower();}
                        <li class="@(controller == "home" ? "active" : null)"><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li class="@(controller == "movies" ? "active" : null)"><a href="@Url.Action("Index", "Movies")">Películas</a></li>
                        <li class="@(controller == "genres" ? "active" : null)"><a href="@Url.Action("Index", "Genres")">Géneros</a></li>
                    </ul>

                    <div class="nav navbar-nav navbar-right">
                        <div style="margin: 15px;">@Html.Partial("_LoginPartial")</div>
                    </div>
                </div>
            </div>

            @if (TempData["successmessage"] != null)
            {
                <div class="alert alert-success">@TempData["successmessage"]</div>

                <br />
            }

            @RenderBody()
        </div>
    </div>

    <div id="footer">
        <div class="container">
            <p class="text-muted">
                Hexacta &copy; 2013 - <a href="mailto:hat@hexacta.com"><span class="glyphicon glyphicon-envelope"></span>&nbsp;HAT</a>
            </p>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>